### PR TITLE
Use Nuget packages for tests

### PR DESCRIPTION
**Pull request by kant2002**

### CODE REVIEW

**Comment by leppie** [comment]
Any idea why NUnit is not being found for the .NET Core test pass?

If not, I could have a look.

**Comment by kant2002** [comment]
Actually I don’t know why. That’s looks like some Appveyor stuff for me. Or. At least I did try repro locally and it was working

**Comment by leppie** [comment]
Did  you run `test.cmd` locally?

**Comment by leppie** [comment]
Can you merge with master? I have added a step  to copy  `nunit.framework.dll` for .NET Core test pass.

**Comment by leppie** [comment]
Oops, that bump was not going as I intended.

**Pull request merged**
